In [1]:
import numpy as np

In [3]:
x = np.array([59.50, 31.40, 19, 22, 60550, 2])

In [4]:
print("ndim:", x.ndim) # число осей (измерений) массива - n.dim: 1
print("shape:", x.shape) # размеры массива, для вектора определена только длина - shape: (6, )


ndim: 1
shape: (6,)


In [7]:
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])
share_living_space = apartment[1]/apartment[0]

In [9]:
apartment = np.delete(apartment, [0, 1])

In [11]:
apartment = np.append(apartment, share_living_space)
apartment

array([1.90000000e+01, 2.20000000e+01, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

In [12]:
round(share_living_space, 2)

0.53

In [13]:
len(apartment)

5

In [14]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [15]:
x = np.array([4, 5])
y = np.array([2, 1])
u = np.array([1, 0])
2*x - 3*y + 5*u

array([7, 7])

In [17]:
x1 = np.array([3, 4, 5, 9])
x2 = np.array([1, 5, 3, 6])
-200*x1 + 400*x2

array([-200, 1200,  200,  600])

In [18]:
x = np.array([4, 5, -1])
y = np.array([2, 0, 1])
np.dot(x, y)

7

In [25]:
x = np.array([4, 6, 1])
s = np.dot(x, x)
s**0.5

7.280109889280518

In [26]:
np.linalg.norm(x)

7.280109889280518