In [1]:
import numpy as np # для работы с массивами
# import pandas as pd # для работы DataFrame 
# import seaborn as sns # библиотека для визуализации статистических данных
# import matplotlib.pyplot as plt # для построения графиков

# %matplotlib inline

In [85]:
x1 = np.array([1,2,1,1]).T
x2 = np.array([70,130,65,60]).T

In [95]:
x1_c = x1-x1.mean()
x2_c = x2-x2.mean()
print(x1_c)
print(x2_c)

[-0.25  0.75 -0.25 -0.25]
[-11.25  48.75 -16.25 -21.25]


In [96]:
x1_c_norm = np.linalg.norm(x1_c)
x2_c_norm = np.linalg.norm(x2_c)
print(x1_c_norm)
print(x2_c_norm)

0.8660254037844386
56.73402858955109


In [97]:
x1_st = x1_c / x1_c_norm
x2_st = x2_c / x2_c_norm
print(x1_st)
print(x2_st)

[-0.28867513  0.8660254  -0.28867513 -0.28867513]
[-0.19829369  0.85927267 -0.28642422 -0.37455475]


In [89]:
A = np.array([
    [1, 0.9922],
    [0.9922, 1]
])
B = np.linalg.eig(A)
B

(array([1.9922, 0.0078]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [90]:
B[1][:,0]

array([0.70710678, 0.70710678])

In [107]:
# pca1 = np.column_stack((x1,x2))@B[1][:,0]
pca1 = np.column_stack((x1_st,x2_st))@np.array([1,1])

In [108]:
pca1_c = pca1 - pca1.mean()
pca1_c_norm = np.linalg.norm(pca1_c)
pca1_st = pca1_c / pca1_c_norm
pca1_st.round(4)

array([-0.244 ,  0.8643, -0.2881, -0.3323])

In [98]:
A1 = np.array([
    [1, -0.77],
    [-0.77, 1]
])
B1 = np.linalg.eig(A1)
B1

(array([1.77, 0.23]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))