In [3]:
import numpy as np
import pandas as pd

In [4]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})


In [5]:
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [8]:
Hut_Paradise_NP = Hut_Paradise_DF.to_numpy()

In [12]:
Hut_Paradise_NP[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

In [13]:
Hut_Paradise_NP[:,1] - Hut_Paradise_NP[:,5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

In [16]:
Hut_Paradise_NP[:,0] / 10 * 4

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]])

In [42]:
time_to_demo = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
time_to_demo = time_to_demo.reshape(-1,1)

In [46]:
Hut_Paradise_NP_ext = np.append(Hut_Paradise_NP, time_to_demo, axis=1)

In [50]:
sum(Hut_Paradise_NP_ext[:,6]*Hut_Paradise_NP_ext[:,4])

1348

In [49]:
Hut_Paradise_NP_ext

array([[ 65,  50,   3,   5,   8,  37,  10],
       [ 70,  52,   2,  12,   4,  40,  20],
       [120,  80,   1,  10,   5,  65,  30],
       [ 35,  33,   1,   3,  10,  20,  15],
       [ 40,  33,   1,   6,  20,  16,   5],
       [ 50,  44,   2,  13,  12,  35,  40],
       [100,  80,   4,   8,   5,  60,  20],
       [ 90,  65,   3,  21,   1,  50,   8],
       [ 85,  65,   2,   5,  10,  40,  20]])

In [51]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])


In [52]:
x = 2 * v - 3 * w

In [53]:
x

array([-3, 14,  3,  4,  2])

In [54]:
np.dot(x,u)

0

In [60]:
u_norm = u / np.linalg.norm(u)
v_norm = v / np.linalg.norm(v)
w_norm = w / np.linalg.norm(w)


In [65]:
print(round(u_norm[2], 3))
print(round(v_norm[3], 3))
print(round(w_norm[0], 3))

0.289
0.667
0.213


In [66]:
Hut_Paradise_DF.to_numpy()

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]])

In [68]:
Hut_Paradise_DF.values

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]])

In [69]:
time_to_demo.reshape(-1,1)

array([[10],
       [20],
       [30],
       [15],
       [ 5],
       [40],
       [20],
       [ 8],
       [20]])

In [70]:
np.reshape(time_to_demo, (len(time_to_demo), 1))

array([[10],
       [20],
       [30],
       [15],
       [ 5],
       [40],
       [20],
       [ 8],
       [20]])

In [71]:
np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])

array([10, 20, 30, 15,  5, 40, 20,  8, 20])

In [73]:
np.array([10, 20, 30, 15, 5, 40, 20, 8, 20], ndmin=2).T

array([[10],
       [20],
       [30],
       [15],
       [ 5],
       [40],
       [20],
       [ 8],
       [20]])