In [1]:
import numpy as np # для работы с массивами
import pandas as pd # для работы DataFrame 
import seaborn as sns # библиотека для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

%matplotlib inline

In [3]:
df = pd.read_csv("./Admission_Predict_Ver1.1.csv")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Serial No.         500 non-null    int64  
 1   GRE Score          500 non-null    int64  
 2   TOEFL Score        500 non-null    int64  
 3   University Rating  500 non-null    int64  
 4   SOP                500 non-null    float64
 5   LOR                500 non-null    float64
 6   CGPA               500 non-null    float64
 7   Research           500 non-null    int64  
 8   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB


In [8]:
df.corr().round(2)

Serial No.  GRE Score  TOEFL Score  University Rating  \
Serial No.               1.00      -0.10        -0.14              -0.07   
GRE Score               -0.10       1.00         0.83               0.64   
TOEFL Score             -0.14       0.83         1.00               0.65   
University Rating       -0.07       0.64         0.65               1.00   
SOP                     -0.14       0.61         0.64               0.73   
LOR                     -0.00       0.52         0.54               0.61   
CGPA                    -0.07       0.83         0.81               0.71   
Research                -0.01       0.56         0.47               0.43   
Chance of Admit          0.01       0.81         0.79               0.69   

                    SOP  LOR   CGPA  Research  Chance of Admit   
Serial No.        -0.14 -0.00 -0.07     -0.01              0.01  
GRE Score          0.61  0.52  0.83      0.56              0.81  
TOEFL Score        0.64  0.54  0.81      0.47              0.79  
University Rating  0.73  0.61  0.71      0.43              0.69  
SOP                1.00  0.66  0.71      0.41              0.68  
LOR                0.66  1.00  0.64      0.37              0.65  
CGPA               0.71  0.64  1.00      0.50              0.88  
Research           0.41  0.37  0.50      1.00              0.55  
Chance of Admit    0.68  0.65  0.88      0.55              1.00

In [9]:
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [12]:
df[df.Research==0].corr().round(2)

Serial No.  GRE Score  TOEFL Score  University Rating  \
Serial No.               1.00      -0.17        -0.19              -0.09   
GRE Score               -0.17       1.00         0.68               0.38   
TOEFL Score             -0.19       0.68         1.00               0.50   
University Rating       -0.09       0.38         0.50               1.00   
SOP                     -0.20       0.37         0.48               0.61   
LOR                     -0.02       0.37         0.47               0.48   
CGPA                    -0.14       0.68         0.70               0.52   
Research                  NaN        NaN          NaN                NaN   
Chance of Admit         -0.00       0.60         0.62               0.43   

                    SOP  LOR   CGPA  Research  Chance of Admit   
Serial No.        -0.20 -0.02 -0.14       NaN             -0.00  
GRE Score          0.37  0.37  0.68       NaN              0.60  
TOEFL Score        0.48  0.47  0.70       NaN              0.62  
University Rating  0.61  0.48  0.52       NaN              0.43  
SOP                1.00  0.62  0.55       NaN              0.47  
LOR                0.62  1.00  0.56       NaN              0.54  
CGPA               0.55  0.56  1.00       NaN              0.75  
Research            NaN   NaN   NaN       NaN               NaN  
Chance of Admit    0.47  0.54  0.75       NaN              1.00

In [13]:
df[df.Research==1].corr().round(2)

Serial No.  GRE Score  TOEFL Score  University Rating  \
Serial No.               1.00      -0.09        -0.14              -0.06   
GRE Score               -0.09       1.00         0.82               0.61   
TOEFL Score             -0.14       0.82         1.00               0.60   
University Rating       -0.06       0.61         0.60               1.00   
SOP                     -0.11       0.61         0.63               0.72   
LOR                      0.01       0.44         0.44               0.57   
CGPA                    -0.05       0.81         0.78               0.69   
Research                  NaN        NaN          NaN                NaN   
Chance of Admit          0.02       0.80         0.79               0.71   

                    SOP  LOR   CGPA  Research  Chance of Admit   
Serial No.        -0.11  0.01 -0.05       NaN              0.02  
GRE Score          0.61  0.44  0.81       NaN              0.80  
TOEFL Score        0.63  0.44  0.78       NaN              0.79  
University Rating  0.72  0.57  0.69       NaN              0.71  
SOP                1.00  0.59  0.72       NaN              0.71  
LOR                0.59  1.00  0.56       NaN              0.59  
CGPA               0.72  0.56  1.00       NaN              0.89  
Research            NaN   NaN   NaN       NaN               NaN  
Chance of Admit    0.71  0.59  0.89       NaN              1.00

In [17]:
toefl = df[df.Research==0][["TOEFL Score"]]
cgpa = df[df.Research==0][["CGPA"]]

In [19]:
A = np.column_stack((np.ones(220), toefl, cgpa))

In [45]:
y = df[df.Research==0][["Chance of Admit "]]

In [58]:
w_hat = np.linalg.inv(A.T@A)@A.T@y
np.linalg.lstsq(A, y, rcond=None)

(array([[-1.04486443],
        [ 0.00442727],
        [ 0.14807744]]),
 array([1.13772786]),
 3,
 array([1.54898055e+03, 5.02503482e+00, 6.75329627e-01]))

In [59]:
w_hat

Chance of Admit 
0         -1.044864
1          0.004427
2          0.148077

In [54]:
w_tmp = w_hat.round(3)

In [94]:
toefl_new=107
cgpa_new=9.1
c = w_tmp.loc[0] + w_tmp.loc[1]*toefl_new + w_tmp.loc[2]*cgpa_new
c

Chance of Admit     0.7298
dtype: float64

In [125]:
toefl_mean = df[df.Research==0]["TOEFL Score"].mean()
cgpa_mean = df[df.Research==0]["CGPA"].mean()
y_mean = df[df.Research==0]["Chance of Admit "].mean()

In [126]:
toefl_c = df[df.Research==0][["TOEFL Score"]] - toefl_mean
cgpa_c = df[df.Research==0][["CGPA"]] - cgpa_mean
y_c = df[df.Research==0][["Chance of Admit "]] - y_mean

In [127]:
toefl_norm = np.linalg.norm(toefl_c)
cgpa_norm = np.linalg.norm(cgpa_c)
y_norm = np.linalg.norm(y_c)

In [128]:
toefl_st = toefl_c / toefl_norm
cgpa_st = cgpa_c / cgpa_norm
y_st = y_c / y_norm

In [129]:
A_st = np.column_stack((toefl_st, cgpa_st))

In [130]:
w_hat_st = np.linalg.inv(A_st.T@A_st)@A_st.T@y_st
w_hat_st

Chance of Admit 
0          0.190448
1          0.620015

In [131]:
toefl_new_st = (toefl_new - toefl_mean) / toefl_norm
cgpa_new_st = (cgpa_new - cgpa_mean) / cgpa_norm

In [133]:
y_new_st = w_hat_st.values[0]*toefl_new_st + w_hat_st.values[1]*cgpa_new_st
print(y_new_st)

[0.08540446]


In [139]:
print(y_new_st * y_norm + y_mean)
print((w_hat.loc[0] + w_hat.loc[1]*toefl_new + w_hat.loc[2]*cgpa_new).values)

[0.77635853]
[0.77635853]
