In [8]:
import numpy as np
import scipy.linalg

In [4]:
user_movie_matrix = np.array(
    (
        (1, 5, 0, 5, 4),
        (5, 4, 4, 3, 2),
        (0, 4, 0, 0, 5),
        (4, 4, 1, 4, 0),
        (0, 4, 3, 5, 0),
        (2, 4, 3, 5, 3),
    )
)
user_movie_matrix


array([[1, 5, 0, 5, 4],
       [5, 4, 4, 3, 2],
       [0, 4, 0, 0, 5],
       [4, 4, 1, 4, 0],
       [0, 4, 3, 5, 0],
       [2, 4, 3, 5, 3]])

In [9]:
U, s, V = scipy.linalg.svd(user_movie_matrix) 

In [22]:
low_U = U[:2]
low_V = V[:2]


In [24]:
lowdim  = user_movie_matrix[2] @ low_V.T
lowdim

array([-4.09679486,  4.68635611])

In [25]:
user2 = lowdim @ low_V
user2

array([-0.6096677 ,  3.54684982, -0.57140075,  1.15887633,  4.9116525 ])

In [27]:
round(5-4.9116525, 3)

0.088

In [30]:
new_user = np.array((0, 0, 3, 4, 0))
new_low_U = U[:3]
new_low_V = V[:3]
lowdim  = new_user @ new_low_V.T
new_user_pred = lowdim @ new_low_V
new_user_pred

array([ 0.40015936,  1.52990144,  1.47154395,  3.57090597, -1.13168846])