In [1]:
import numpy as np

In [2]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))


Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [3]:
np.sqrt(a)

array([1.73205081, 2.44948974, 3.        ])

In [4]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])


In [5]:
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [7]:
my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5))

array([[3, 8, 4, 8, 0],
       [5, 2, 4, 3, 7],
       [2, 2, 4, 5, 7],
       [8, 0, 4, 8, 1]])

In [8]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [9]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[3, 7, 8, 6],
       [8, 9, 5, 8],
       [2, 5, 7, 8]])

In [12]:
my_array < 5

array([[ True, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [13]:
my_array[my_array<5]

array([3, 2])

In [14]:
mask = np.array([1, 0, 1, 0], dtype=bool)
mask

array([ True, False,  True, False])

In [15]:
my_array[:, mask]

array([[3, 8],
       [8, 5],
       [2, 7]])

In [16]:
my_array = np.random.randint(0, 10, (4, 6))
my_array

array([[9, 6, 9, 0, 1, 4],
       [4, 0, 0, 0, 2, 8],
       [7, 5, 5, 6, 8, 4],
       [2, 5, 1, 3, 9, 5]])

In [17]:
np.sort(my_array, axis=1)

array([[0, 1, 4, 6, 9, 9],
       [0, 0, 0, 2, 4, 8],
       [4, 5, 5, 6, 7, 8],
       [1, 2, 3, 5, 5, 9]])

In [18]:
np.sort(my_array, axis=0)

array([[2, 0, 0, 0, 1, 4],
       [4, 5, 1, 0, 2, 4],
       [7, 5, 5, 3, 8, 5],
       [9, 6, 9, 6, 9, 8]])

In [19]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T
great_secret

array([[ 0.        ,  4.64158883, 66.66666667],
       [ 1.        ,  4.65700951, 40.        ],
       [ 1.41421356,  4.67232873, 67.33333333],
       [ 1.73205081,  4.68754815, 40.4       ],
       [ 2.        ,  4.70266938, 68.        ],
       [ 2.23606798,  4.71769398, 40.8       ],
       [ 2.44948974,  4.73262349, 68.66666667],
       [ 2.64575131,  4.7474594 , 41.2       ],
       [ 2.82842712,  4.76220316, 69.33333333],
       [ 3.        ,  4.77685618, 41.6       ],
       [ 3.16227766,  4.79141986, 70.        ],
       [ 3.31662479,  4.80589553, 42.        ],
       [ 3.46410162,  4.82028453, 70.66666667],
       [ 3.60555128,  4.83458813, 42.4       ],
       [ 3.74165739,  4.84880759, 71.33333333],
       [ 3.87298335,  4.86294413, 42.8       ],
       [ 4.        ,  4.87699896, 72.        ],
       [ 4.12310563,  4.89097325, 43.2       ],
       [ 4.24264069,  4.90486813, 72.66666667],
       [ 4.35889894,  4.91868473, 43.6       ],
       [ 4.47213595,  4.93242415, 73.333

# Задание 2
Чему равна сумма косинусов элементов первой строки массива great_secret? Ответ округлите до двух знаков после запятой.

In [32]:
round(np.sum(np.cos(great_secret[0,:])),2)

0.16

In [22]:
my_array = np.random.randint(0, 10, (4, 6))
my_array

array([[3, 4, 6, 2, 3, 9],
       [2, 4, 8, 2, 9, 5],
       [3, 2, 9, 9, 1, 3],
       [3, 9, 0, 5, 2, 7]])

In [26]:
my_array[0,:]

array([3, 4, 6, 2, 3, 9])

# Задание 3
Чему равна сумма элементов массива great_secret, значение которых больше 50?

In [34]:
np.sum(great_secret[great_secret>50])

5470.0

# Задание 4
Переведите массив great_secret в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150? Скопируйте ответ из Jupyter Notebook без изменений.

In [38]:
great_secret.flatten()[150]

7.0710678118654755

# Задание 5
Отсортируйте значения столбцов массива great_secret по возрастанию. Чему равна сумма элементов последней строки отсортированного массива? Ответ округлите до двух цифр после запятой.

In [42]:
round(np.sum(np.sort(great_secret, axis=0)[-1,:]),2)

115.12