In [1]:
import numpy as np
import pandas as pd

In [4]:
arr1 = np.array([1,2,3,4])

In [7]:
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype

dtype('float64')

In [8]:
arr2

array([5., 6., 7., 8.])

In [9]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
np.shape(arr3)

(3, 3)

In [11]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [16]:
my_series = pd.Series([5, 6, 7, 8, 9, 10])
type(my_series)
type(my_series.values)

numpy.ndarray

In [20]:
np.empty(5, dtype = "int64")

array([4607182418800017408, 4613374868287651840, 4618441417868443648,
       4622241330054037504, 4625478292286210048])

In [22]:
np.zeros((10, 7), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [23]:
np.ones((3,3,3), dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.arange(0, 21, 7)

array([ 0,  7, 14])

In [31]:
np.linspace(0, 1, 51)

array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98, 1.  ])

In [32]:
[x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]


[1, 57, 71, 127, 141, 197, 211, 267, 281]

In [36]:
np.full((5,5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.random.randint(0, 5, 3)

array([4, 2, 3])

In [39]:
np.ones((4, 4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.arange(1, 14, 2)

array([ 1,  3,  5,  7,  9, 11, 13])