In [9]:
import numpy as np

In [4]:
student_id = range(1,11)
list(student_id)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
student_height = [135,160,163,147,138,149,136,154,137,165]
student_height


[135, 160, 163, 147, 138, 149, 136, 154, 137, 165]

In [7]:
student_weight = [34,43,40,44,41,54,39,48,35,60]
student_weight

[34, 43, 40, 44, 41, 54, 39, 48, 35, 60]

In [8]:
student_score = [4,5,4.3,5,4.7,3.9,4.2,4.9,3.7,4.6]
student_score

[4, 5, 4.3, 5, 4.7, 3.9, 4.2, 4.9, 3.7, 4.6]

In [12]:
students = np.array([student_id, student_height, student_weight, student_score]).T
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [13]:
mean = np.mean(students[:,-1])
mean

4.430000000000001

In [14]:
median = np.median(students[:,-1])
median

4.449999999999999

# Задание 1
Чему равно медианное значение массы тела школьников?

In [15]:
median = np.median(students[:,-2])
median

42.0

In [17]:
np.mean(students[:,-2]) - np.median(students[:,-2])


1.7999999999999972

In [18]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [19]:
corr = np.corrcoef(students[:,1], students[:,-1])
corr

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

In [20]:
corr = np.corrcoef(students[:,2], students[:,-1])
corr

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [21]:
std = np.std(students[:,1])
std

11.083320801997928

# Задание 4
Используя имеющийся набор данных о школьниках, найдите, чему равно стандартное отклонение их средних баллов.


In [22]:
std = np.std(students[:,-1])
std

0.4517742799230607

# Задание 5
Посчитайте, чему равна дисперсия значений веса школьников.
Эту величину можно получить двумя способами: математически - используя определение дисперсии и известную функцию в блоке, или самостоятельно - используя подходящую функцию модуля NumPy.

In [25]:
np.var(students[:,2])

60.36

In [26]:
np.full((10, 5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [28]:
my_array[1:4, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

# Задание 5
Создайте массив my_sin, состоящий из синусов элементов массива my_array. Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до трёх цифр после запятой.



In [29]:
my_sin = np.sin(my_array)

In [30]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [31]:
round(np.sum(my_sin), 3)

-0.058

# Задание 6
Замените элементы в центральном фрагменте 3 х 3 массива my_sin на единицы.Чему равна сумма элементов изменённого массива? Ответ округлите до трёх знаков после запятой.

In [33]:
my_sin[1:4,1:4]=1

In [35]:
round(np.sum(my_sin), 3)

7.572

# Задание 7
Преобразуйте первые четыре столбца массива my_sin в массив из 10 строк и 2 столбцов. Чему равна сумма элементов первого столбца получившегося массива? Ответ округлите до трёх заков после точки-разделителя. Используйте преобразованный в предыдущем задании массив my_sin.

In [39]:
my_sin[:,:4]

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.2794155 ,  1.        ,  1.        ,  1.        ],
       [-0.99999021,  1.        ,  1.        ,  1.        ],
       [-0.28790332,  1.        ,  1.        ,  1.        ],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836]])

In [41]:
np.reshape(my_sin[:,:4], (10,2))

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.2794155 ,  1.        ],
       [ 1.        ,  1.        ],
       [-0.99999021,  1.        ],
       [ 1.        ,  1.        ],
       [-0.28790332,  1.        ],
       [ 1.        ,  1.        ],
       [ 0.83665564, -0.00885131],
       [-0.8462204 , -0.90557836]])

In [42]:
round(np.sum(np.reshape(my_sin[:,:4], (10,2))[:,0]),3)

2.406

# Подготовка массива к заданиям 8-10
Создайте массив bigdata, содержащий квадраты всех нечётных чисел в диапазоне от 100 до 1000.

In [45]:
bigdata = np.array([x**2 for x in range(100,1000) if x%2])

# Задание 8
Чему равна медиана массива bigdata?

In [47]:
np.median(bigdata)

302501.0

# Задание 9
Чему равно стандартное отклонение для массива bigdata? Ответ округлите до целых:

In [48]:
round(np.std(bigdata))

292095

# Задание 10
Чему равен коэффициент корреляции между элементами массива bigdata с чётными и нечётными индексами? Введите полученный ответ без изменений и округлений.

In [54]:
np.corrcoef(bigdata[0::2], bigdata[1::2])

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])