In [1]:
import numpy as np

In [29]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

# Задание 1
Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:

In [32]:
round(sum(big_secret[:,-1]), 2)

3154.33

In [11]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [12]:
my_array[:,-1]

array([ 4, 13, 48])

In [27]:
my_array[0:2,-1]

array([ 4, 13])

# Задание 2
Выделите из каждой строки массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после запятой:

In [43]:
i = 0.0
for indx, line in enumerate(big_secret[:, :5]):
    i += line[indx]
round(i,2)

121.37

In [41]:
big_secret[:, :5]

array([[14.        , 10.        ,  6.        , 56.        , 40.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [ 0.        ,  1.        ,  4.        ,  9.        , 16.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [14.        , 10.        ,  6.        , 56.        , 40.        ]])

# Задание 3
Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.


In [47]:
i = 1.0
for indx, line in enumerate(big_secret[:, -5:]):
    i *= line[indx]
round(i,2)

341505315559.23

In [49]:
my_array = np.random.randint(1, 100, (4, 6)) 
my_array

array([[49,  5, 63, 99,  5, 98],
       [83, 69, 95, 75, 30, 99],
       [26, 42, 89, 62, 90, 22],
       [90, 75, 27, 68, 12, 44]])

In [50]:
my_slice = my_array[1:3, 2:4]
my_slice

array([[95, 75],
       [89, 62]])

In [52]:
my_slice[:] = 0

In [53]:
my_array

array([[49,  5, 63, 99,  5, 98],
       [83, 69,  0,  0, 30, 99],
       [26, 42,  0,  0, 90, 22],
       [90, 75, 27, 68, 12, 44]])

# Упражнения

Проверим знания! Продолжим работать с массивом big_secret. Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.

In [57]:
my_array

array([[49,  5, 63, 99,  5, 98],
       [83, 69,  0,  0, 30, 99],
       [26, 42,  0,  0, 90, 22],
       [90, 75, 27, 68, 12, 44]])

In [59]:
my_array[1::2,1::2]

array([[69,  0, 99],
       [75, 68, 44]])

In [62]:
slice1 = big_secret[1::2,1::2]
slice1[:] = 1

In [64]:
slice2 = big_secret[0::2,0::2]
slice2[:] = -1

In [65]:
big_secret

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

# Задание 4
Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.


In [66]:
i = 0.0
for indx, line in enumerate(big_secret[:, :5]):
    i += line[indx]
i

-1.0

# Задание 5
Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [67]:
i = 1.0
for indx, line in enumerate(big_secret[:, -5:]):
    i *= line[indx]
i

-1.0